= Spring Cloud Zuul RateLimit

== 整体介绍
在zuul中，可以启用针对每个服务来限流
有5种内置的限流方式:

 * 登录用户
 ** 使用登录名或匿名anonymous
 * 用户IP地址
 ** 使用用户的IP请求地址来限流
 * URL
 ** 使用用户的请求path来限流
 * URL匹配
 ** 使用用户的请求path的匹配模式来限流
 * 登录用户角色
 ** 使用登录用户的不同角色来限流
 * 针对请求方法
 ** 使用用户请求的方法来限流，如POST|GET|DELETE
 * 针对服务:
 ** 这种方式不会校验IP地址、登录用户、还有URI等、
 ** 使用这个方式，不可以在配置中使用type

[注意]
====
也可以组合登录用户、IP地址、URL、登录角色、请求方法等限流方式来一起使用
====

== 怎么使用
在pom.xml增加以下依赖

[source, xml]
----
<dependency>
    <groupId>com.marcosbarbero.cloud</groupId>
    <artifactId>spring-cloud-zuul-ratelimit</artifactId>
    <version>LATEST</version>
</dependency>
----

在限流中可以使用以下的存储方案

* Redis

[source, xml]
----
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-data-redis</artifactId>
</dependency>
----

* Consul

[source, xml]
----
<dependency>
   <groupId>org.springframework.cloud</groupId>
   <artifactId>spring-cloud-starter-consul</artifactId>
</dependency>
----

* Spring Data JPA

[source, xml]
----
<dependency>
   <groupId>org.springframework.boot</groupId>
   <artifactId>spring-boot-starter-data-jpa</artifactId>
</dependency>
----

* Bucket4j JCache

[source, xml]
----
<dependency>
     <groupId>com.github.vladimir-bukhtoyarov</groupId>
     <artifactId>bucket4j-core</artifactId>
</dependency>
<dependency>
     <groupId>com.github.vladimir-bukhtoyarov</groupId>
     <artifactId>bucket4j-jcache</artifactId>
</dependency>
<dependency>
     <groupId>javax.cache</groupId>
     <artifactId>cache-api</artifactId>
</dependency>
----

* Bucket4j Hazelcast (depends on Bucket4j JCache)

[source, xml]
----
<dependency>
     <groupId>com.github.vladimir-bukhtoyarov</groupId>
     <artifactId>bucket4j-hazelcast</artifactId>
</dependency>
<dependency>
     <groupId>com.hazelcast</groupId>
     <artifactId>hazelcast</artifactId>
</dependency>
----

* Bucket4j Infinispan (depends on Bucket4j JCache)

[source, xml]
----
<dependency>
     <groupId>com.github.vladimir-bukhtoyarov</groupId>
     <artifactId>bucket4j-infinispan</artifactId>
</dependency>
<dependency>
     <groupId>org.infinispan</groupId>
     <artifactId>infinispan-core</artifactId>
</dependency>
----

* Bucket4j Ignite (depends on Bucket4j JCache)

[source, xml]
----
<dependency>
     <groupId>com.github.vladimir-bukhtoyarov</groupId>
     <artifactId>bucket4j-ignite</artifactId>
</dependency>
<dependency>
     <groupId>org.apache.ignite</groupId>
     <artifactId>ignite-core</artifactId>
</dependency>
----

限流的一个简单配置例子
[source, yaml]
----
zuul:
  ratelimit:
    key-prefix: your-prefix 
    enabled: true   #是否开启限流开关
    repository: REDIS   #限流数据的存储方式，REDIS。  默认是内存
    behind-proxy: true  #是否开启代理
    add-response-headers: true  #在返回头部是否增加限流信息
    default-policy-list: #全局的默认限流策略。如果在自定义限流未找到合适的，就会使用默认的限流方案
      - limit: 10 #optional - 每个单位时间窗口内的最大请求数
        quota: 1000 #optional - 单位时间窗口内所有请求耗时的最大限制，单位秒
        refresh-interval: 60 #每个单位时间窗口，默认1秒。这里设置60秒即1分钟
        type: #限流方式。 按登录人、按请求的IP地址、按url、按请求的方法
          - user
          - origin
          - url
          - http_method
    policy-list:    #自定义限流策略
      myServiceId:  #注册中心服务的serviceId值
        - limit: 10
          quota: 1000
          refresh-interval:
          type: #optional
            - user
            - origin
            - url
        - type: #optional value for each type
            - user=anonymous
            - origin=somemachine.com
            - url=/api #url prefix
            - role=user
            - http_method=get #case insensitive
        - type:
            - url_pattern=/api/*/payment
----

简单例子配置
[source, properties]
----
zuul.ratelimit.enabled=true
zuul.ratelimit.key-prefix=your-prefix
zuul.ratelimit.repository=REDIS
zuul.ratelimit.behind-proxy=true
zuul.ratelimit.add-response-headers=true

zuul.ratelimit.default-policy-list[0].limit=10
zuul.ratelimit.default-policy-list[0].quota=1000
zuul.ratelimit.default-policy-list[0].refresh-interval=60

# Adding multiple rate limit type
zuul.ratelimit.default-policy-list[0].type[0]=user
zuul.ratelimit.default-policy-list[0].type[1]=origin
zuul.ratelimit.default-policy-list[0].type[2]=url
zuul.ratelimit.default-policy-list[0].type[3]=http_method

# Adding the first rate limit policy to "myServiceId"
zuul.ratelimit.policy-list.myServiceId[0].limit=10
zuul.ratelimit.policy-list.myServiceId[0].quota=1000
zuul.ratelimit.policy-list.myServiceId[0].refresh-interval=60
zuul.ratelimit.policy-list.myServiceId[0].type[0]=user
zuul.ratelimit.policy-list.myServiceId[0].type[1]=origin
zuul.ratelimit.policy-list.myServiceId[0].type[2]=url

# Adding the second rate limit policy to "myServiceId"
zuul.ratelimit.policy-list.myServiceId[1].type[0]=user=anonymous
zuul.ratelimit.policy-list.myServiceId[1].type[1]=origin=somemachine.com
zuul.ratelimit.policy-list.myServiceId[1].type[2]=url_pattern=/api/*/payment
zuul.ratelimit.policy-list.myServiceId[1].type[3]=role=user
zuul.ratelimit.policy-list.myServiceId[1].type[4]=http_method=get
----

== 限流实现方式

提供了8种方案:

[cols=2*, options="header"]
|===
|实现        | 数据存储

|ConsulRateLimiter     | https://www.consul.io/[Consul]

|RedisRateLimiter      | https://redis.io/[Redis]

|SpringDataRateLimiter | https://projects.spring.io/spring-data-jpa/[Spring Data]

|Bucket4jJCacheRateLimiter

.4+.^|https://github.com/vladimir-bukhtoyarov/bucket4j[Bucket4j]

|Bucket4jHazelcastRateLimiter

|Bucket4jIgniteRateLimiter

|Bucket4jInfinispanRateLimiter

|===

Bucket4j实现需要在项目配置 `@Qualifier("RateLimit")`Bean实例:

 * `JCache` - javax.cache.Cache
 * `Hazelcast` - com.hazelcast.core.IMap
 * `Ignite` - org.apache.ignite.IgniteCache
 * `Infinispan` - org.infinispan.functional.ReadWriteMap
 
== 通用的限流属性

Property namespace: __zuul.ratelimit__

|===
|属性名称| 属性值 |默认值

|enabled             |true/false                   |false
|behind-proxy        |true/false                   |false
|add-response-headers|true/false                   |true
|key-prefix          |String                       |${spring.application.name:rate-limit-application}
|repository          |CONSUL, REDIS, JPA, BUCKET4J_JCACHE, BUCKET4J_HAZELCAST, BUCKET4J_INFINISPAN, BUCKET4J_IGNITE| -
|default-policy-list |List of link:./spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/properties/RateLimitProperties.java#L82[Policy]| -
|policy-list         |Map of Lists of link:./spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/properties/RateLimitProperties.java#L82[Policy]| -
|postFilterOrder     |int                          |FilterConstants.SEND_RESPONSE_FILTER_ORDER - 10
|preFilterOrder      |int                          |FilterConstants.FORM_BODY_WRAPPER_FILTER_ORDER

|===

限流策略属性:

|===
|属性名称| 属性值 |默认值

|limit           |调用的次数      |  -
|quota           |调用所耗的时间        |  -
|refresh-interval|单位时间窗口的刷新时间              | 60秒
|type            | [ORIGIN, USER, URL, URL_PATTERN, ROLE, HTTP_METHOD] | []
|breakOnMatch    |true/false           |false

|===

== 可以做进一步定制的实现

这部分详细告诉您怎么增加自定义实现类

=== Key生成策略
如果现在提供的key生成策略不满足你，你可以自己创建自定义的key生成策略，来满足更适合您自己的内容

[source, java]
----
  @Bean
  public RateLimitKeyGenerator ratelimitKeyGenerator(RateLimitProperties properties, RateLimitUtils rateLimitUtils) {
      return new DefaultRateLimitKeyGenerator(properties, rateLimitUtils) {
          @Override
          public String key(HttpServletRequest request, Route route, RateLimitProperties.Policy policy) {
              return super.key(request, route, policy) + ":" + request.getMethod();
          }
      };
  }
----

=== 错误处理器
框架使用默认的错误处理器，在控制台输出错误日志，如果你不想在控制台输出，可以自定义错误处理器，比如直接返回统一的json错误信息

[source, java]
----
  @Bean
  public RateLimiterErrorHandler rateLimitErrorHandler() {
    return new DefaultRateLimiterErrorHandler() {
        @Override
        public void handleSaveError(String key, Exception e) {
            // custom code
        }
        
        @Override
        public void handleFetchError(String key, Exception e) {
            // custom code
        }
        
        @Override
        public void handleError(String msg, Exception e) {
            // custom code
        }
    }
  }
----