= Spring Cloud Zuul RateLimit

== 整体介绍
在zuul中，可以启用针对每个服务来限流
有5种内置的限流方式:

 * 登录用户
 ** 使用登录名或匿名anonymous
 * 用户IP地址
 ** 使用用户的IP请求地址来限流
 * URL
 ** 使用用户的请求path来限流
 * URL匹配
 ** 使用用户的请求path的匹配模式来限流
 * 登录用户角色
 ** 使用登录用户的不同角色来限流
 * 针对请求方法
 ** 使用用户请求的方法来限流，如POST|GET|DELETE
 * 针对服务:
 ** 这种方式不会校验IP地址、登录用户、还有URI等、
 ** 使用这个方式，不可以在配置中使用type

在限流中可以使用以下的存储方案

* Redis

[source, xml]
----
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-data-redis</artifactId>
</dependency>
----

* Consul

[source, xml]
----
<dependency>
   <groupId>org.springframework.cloud</groupId>
   <artifactId>spring-cloud-starter-consul</artifactId>
</dependency>
----

* Spring Data JPA

[source, xml]
----
<dependency>
   <groupId>org.springframework.boot</groupId>
   <artifactId>spring-boot-starter-data-jpa</artifactId>
</dependency>
----

* Bucket4j JCache

[source, xml]
----
<dependency>
     <groupId>com.github.vladimir-bukhtoyarov</groupId>
     <artifactId>bucket4j-core</artifactId>
</dependency>
<dependency>
     <groupId>com.github.vladimir-bukhtoyarov</groupId>
     <artifactId>bucket4j-jcache</artifactId>
</dependency>
<dependency>
     <groupId>javax.cache</groupId>
     <artifactId>cache-api</artifactId>
</dependency>
----

* Bucket4j Hazelcast (depends on Bucket4j JCache)

[source, xml]
----
<dependency>
     <groupId>com.github.vladimir-bukhtoyarov</groupId>
     <artifactId>bucket4j-hazelcast</artifactId>
</dependency>
<dependency>
     <groupId>com.hazelcast</groupId>
     <artifactId>hazelcast</artifactId>
</dependency>
----

* Bucket4j Infinispan (depends on Bucket4j JCache)

[source, xml]
----
<dependency>
     <groupId>com.github.vladimir-bukhtoyarov</groupId>
     <artifactId>bucket4j-infinispan</artifactId>
</dependency>
<dependency>
     <groupId>org.infinispan</groupId>
     <artifactId>infinispan-core</artifactId>
</dependency>
----

* Bucket4j Ignite (depends on Bucket4j JCache)

[source, xml]
----
<dependency>
     <groupId>com.github.vladimir-bukhtoyarov</groupId>
     <artifactId>bucket4j-ignite</artifactId>
</dependency>
<dependency>
     <groupId>org.apache.ignite</groupId>
     <artifactId>ignite-core</artifactId>
</dependency>
----

限流的一个简单配置例子
[source, yaml]
----
zuul:
  ratelimit:
    key-prefix: your-prefix 
    enabled: true   #是否开启限流开关
    repository: REDIS   #限流数据的存储方式，REDIS。  默认是内存
    behind-proxy: true  #是否开启代理
    add-response-headers: true  #在返回头部是否增加限流信息
    default-policy-list: #全局的默认限流策略。如果在自定义限流未找到合适的，就会使用默认的限流方案
      - limit: 10 #optional - 每个单位时间窗口内的最大请求数
        quota: 1000 #optional - 单位时间窗口内所有请求耗时的最大限制，单位秒
        refresh-interval: 60 #每个单位时间窗口，默认1秒。这里设置60秒即1分钟
        type: #限流方式。 按登录人、按请求的IP地址、按url、按请求的方法
          - user
          - origin
          - url
          - http_method
    policy-list:    #自定义限流策略
      myServiceId:  #注册中心服务的serviceId值
        - limit: 10
          quota: 1000
          refresh-interval:
          type: #optional
            - user
            - origin
            - url
        - type: #optional value for each type
            - user=anonymous
            - origin=somemachine.com
            - url=/api #url prefix
            - role=user
            - http_method=get #case insensitive
        - type:
            - url_pattern=/api/*/payment
----

== 限流实现方式

提供了8种方案:

[cols=2*, options="header"]
|===
|实现        | 数据存储

|ConsulRateLimiter     | https://www.consul.io/[Consul]

|RedisRateLimiter      | https://redis.io/[Redis]

|SpringDataRateLimiter | https://projects.spring.io/spring-data-jpa/[Spring Data]

|Bucket4jJCacheRateLimiter

.4+.^|https://github.com/vladimir-bukhtoyarov/bucket4j[Bucket4j]

|Bucket4jHazelcastRateLimiter

|Bucket4jIgniteRateLimiter

|Bucket4jInfinispanRateLimiter

|===

Bucket4j实现需要在项目配置 `@Qualifier("RateLimit")`Bean实例:

 * `JCache` - javax.cache.Cache
 * `Hazelcast` - com.hazelcast.core.IMap
 * `Ignite` - org.apache.ignite.IgniteCache
 * `Infinispan` - org.infinispan.functional.ReadWriteMap
 
== 通用的限流属性

Property namespace: __zuul.ratelimit__

|===
|属性名称| 属性值 |默认值

|enabled             |true/false                   |false
|behind-proxy        |true/false                   |false
|add-response-headers|true/false                   |true
|key-prefix          |String                       |${spring.application.name:rate-limit-application}
|repository          |CONSUL, REDIS, JPA, BUCKET4J_JCACHE, BUCKET4J_HAZELCAST, BUCKET4J_INFINISPAN, BUCKET4J_IGNITE| -
|default-policy-list |List of link:./spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/properties/RateLimitProperties.java#L82[Policy]| -
|policy-list         |Map of Lists of link:./spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/properties/RateLimitProperties.java#L82[Policy]| -
|postFilterOrder     |int                          |FilterConstants.SEND_RESPONSE_FILTER_ORDER - 10
|preFilterOrder      |int                          |FilterConstants.FORM_BODY_WRAPPER_FILTER_ORDER

|===

限流策略属性:

|===
|属性名称| 属性值 |默认值

|limit           |调用的次数      |  -
|quota           |调用所耗的时间        |  -
|refresh-interval|单位时间窗口的刷新时间              | 60秒
|type            | [ORIGIN, USER, URL, URL_PATTERN, ROLE, HTTP_METHOD] | []
|breakOnMatch    |true/false           |false

|===

== 可以做进一步定制的实现

这部分详细告诉您怎么增加自定义实现类

=== Key生成策略
如果现在提供的key生成策略不满足你，你可以自己创建自定义的key生成策略，来满足更适合您自己的内容

[source, java]
----
  @Bean
  public RateLimitKeyGenerator ratelimitKeyGenerator(RateLimitProperties properties, RateLimitUtils rateLimitUtils) {
      return new DefaultRateLimitKeyGenerator(properties, rateLimitUtils) {
          @Override
          public String key(HttpServletRequest request, Route route, RateLimitProperties.Policy policy) {
              return super.key(request, route, policy) + ":" + request.getMethod();
          }
      };
  }
----

=== 错误处理器
框架使用默认的错误处理器，在控制台输出错误日志，如果你不想在控制台输出，可以自定义错误处理器，比如直接返回统一的json错误信息

[source, java]
----
  @Bean
  public RateLimiterErrorHandler rateLimitErrorHandler() {
    return new DefaultRateLimiterErrorHandler() {
        @Override
        public void handleSaveError(String key, Exception e) {
            // custom code
        }
        
        @Override
        public void handleFetchError(String key, Exception e) {
            // custom code
        }
        
        @Override
        public void handleError(String msg, Exception e) {
            // custom code
        }
    }
  }
----

== 限流算法
=== 计数器算法：基于信号量Semaphore
- 只有数量维度，没有时间维度

=== 计数器算法：基于fixed window。 固定时间窗口
- 带上了时间维度，不过在两个窗口的临界点容易出现超出限流的情况
比如限制每分钟10个请求，在00:59请求了10次，在01:01又请求了10次，而从00:30-01:30这个时间窗口来看，
这一分钟请求了20次，没有控制好

=== 基于rolling window
- 解决fixed window没解决的窗口临界问题，主要有基于token bucket的算法，以及基于leaky bucket的算法

==== token bucket令牌桶算法
一个存放固定容量令牌的桶，按照固定速率往桶里添加令牌。

- 令牌将按照固定的速率被放入令牌桶中。比如每秒放10个。
- 桶中最多存放b个令牌，当桶满时，新添加的令牌被丢弃或拒绝。
- 当一个n个字节大小的数据包到达，将从桶中删除n个令牌，接着数据包被发送到网络上。
- 如果桶中的令牌不足n个，则不会删除令牌，且该数据包将被限流（要么丢弃，要么缓冲区等待）。

- 例子：
假如我们现在是国庆放假，故宫要做限流措施，对故宫的游客数量进行控制。因此工作人员准备半个小时，派出100张票，
也就是每半个小时生成100张票。假如游人很多，那么每次100张票都能在半小时内用完，其他游客没票了，只能在外面等着，
不让进。那假如游人很少，半个小时100张没用完，那么就会累积在那儿，半个小时后又新生成100张。
因此售票处的票会越来越累积起来。假如突然来了一个大型旅行团，游客数量很多，那么此时由于前面还累积了很多票，
因此即使这个旅行团超过100，也能使他们每个人都有票。

- 能够限制数据的平均传输速率外，还允许某种程度的突发传输

==== leaky bucket漏桶算法
- 一个固定容量的漏桶，按照常量固定速率流出水滴；
- 如果桶是空的，则不需流出水滴；
- 可以以任意速率流入水滴到漏桶
- 如果流入水滴超出了桶的容量，则流入的水滴溢出了（被丢弃），而漏桶容量是不变的。
- 能够强行限制数据的传输速率








